# Manifest for Keller et al, 2012 data
[source]
doi = "10.1186/1471-2202-13-122"
url = "https://bmcneurosci.biomedcentral.com/articles/10.1186/1471-2202-13-122"
title = "An olfactory demography of a diverse metropolitan population"
authors = "A Keller, M Hempstead, IA Gomez, AN Gilbert, LB Vosshall"
tags = "human;intensity;pleasantness;odorCharacter;threshold;academic"

[raw]
"12868_2012_2787_MOESM1_ESM.xlsx" = "Raw data from the supplementary materials"

[processed]
"main.py" = "Processing workflow"
"molecules.csv" = "Information about odorant molecules used"
"mixtures.csv" = "Molecular composition and concentration of the odorants used"
"behavior_1.csv" = "Detection thresholds for 3 odorants"
"behavior_2.csv" = "Descriptors for 3 odorants"
"behavior_3.csv" = "Intensity for 134 odorants"
"behavior_4.csv" = "Pleasantness for 134 odorants"
"subjects.csv" = "Subject metadata"
"substances.csv" = "Stimuli that do not have CID's"
