# Manifest for Manoel et al, 2021 data
[source]
doi = "10.1038/s41586-020-2891-7"
title = "Deconstructing the mouse olfactory percept through an ethological atlas"
tags = "rodent;odorCharacter;academic"
authors = "D Manoel, M Makhlouf, CJ Arayata, A Sathappan, S Daâ€™as, D Abdelrahman, S Selvaraj, R Hasnah, JD Mainland, RC Gerkin, LR Saraiva"

[raw]
"raw_behavioral_scores_mouse_73_odorants.csv" = "Raw scored behaviors for each mouse and odorant"
"SmilesInfo2.xlsx" = "Information about each odorant"

[processed]
"molecules.csv" = "Information about odorant molecules used"
"behavior.csv" = "Scored behaviors for each mouse and odorant"
"stimuli.csv" = "Maps stimulus to CID"

[code]
"main.py" = "Processing workflow"
