# Manifest for Abraham et al, 2012 data
[source]
doi = "10.1093/chemse/bjr094"
title = "An Algorithm for 353 Odor Detection Thresholds in Humans"
authors = "MH Abraham, R Sánchez-Moreno, JE Cometto-Muñiz, WS Cain"

[raw]
ThresholdsAbraham2011.xls = "Data scraped from in-line tables"

[processed]
main.ipynb = "Processing workflow"
molecules.csv = "Molecules used"
behavior.csv = "Compiled odor thresholds and threshold algorithm parameters"
