# Manifest for Wakayama et al, 2019 data
[source]
doi = "10.1021/acs.iecr.9b01225"
title = "Method for Predicting Odor Intensity of Perfumery Raw Materials Using Doseâ€“Response Curve Database"
authors = "H Wakayama, M Sakasai, K Yoshikawa, M Inoue"

[raw]
wakayama-intensity.txt = "Data scraped from supplemental pdf"

[processed]
main.ipynb = "Processing workflow"
molecules.csv = "Molecules used"
behavior.csv = "Supratheshold intensity curve parameters"
