# Manifest for Mayhew et al 2022 Drawing the Borders of Olfactory Space dataset
[source]
doi = "10.1073/pnas.2116576119"
title = "Drawing the Borders of Olfactory Space"
authors = "EJ Mayhew, CJ Arayata, RC Gerkin, BK Lee, M Magill, LL Snyder, KA Little, CW Yu, JD Mainland"
tags = "human;academic"
extra = "Copyright 2021 Emily Mayhew, Rick Gerkin, Brian Lee, Joel Mainland"

[raw]
"S1.csv" = "Molecules used for training and testing, and model probabilities"
"S2.csv" = "Behavioral results"
"S3.csv" = "Transport propertie for a random subset of GDB-17"

[processed]
"molecules.csv" = "Information about odorant molecules used"
"behavior_1.csv" = "Data from S1.csv minus Dragon desriptors"
"behavior_2.csv" = "Data from S2.csv"
"physcis.csv" = "Data from s3.csv; transprot features for GDB-17 molecules"
"stimuli.csv" = "Maps SMILES (stimulus) to CID"

[code]
"main.py" = "Processing workflow"