# Manifest for Chae et al, 2019 data
[source]
doi = "10.1038/s41593-019-0442-z"
title = ""
authors = "H Chae, DR Kepple, WG Bast, VN Murthy, AA Koulakov, DF Albeanu"

[raw]

./mosaic_representations/glomerular_data/glomerular_responses__main
	./animal_#N/left_hemibulb/left_hemibulb_ROI_responses.mat = "glomerular data, left bulb"
	./animal_#N/right_hemibulb/right_hemibulb_ROI_responses.mat = "glomerular data, right bulb"

./mosaic_representations/MT_cell/mitral_cells
	./33_odors/mc_field_of_view_N.mat = "cellular data, for the 33 odorant panel"
	./55_odors/mh_field_of_view_N.mat = "cellular data, for the 55 odorant panel; @ HIGH concentration"
	./55_odors/ml_field_of_view_N.mat = "cellular data, for the 55 odorant panel; @ LOW concentration"
	


./mosaic_representations/MT_cell/tufted_cells
	./th_field_of_view_1.mat = "cellular data, for the 55 odorant panel; @ HIGH concentration"


[processed]

./main.py = "Processing workflow"

./pyrfumeData/behavior_glom.csv = "dF/F responses for all glomerular data, in long format (all subjects & conditions)

./pyrfumeData/behavior_mitral33.csv = "dF/F responses for all mitral cells in the 33 odorant panel experiments; long format
"

./pyrfumeData/behavior_mitral55.csv = "dF/F responses for all mitral cells in the 55 odorant panel experiments; long format"

./pyrfumeData/behavior_tufted.csv = "dF/F responses for all tufted cells (55 odorant panel); long format

./pyrfumeData/molecules.csv = "merged list of molecules used across all experiments (glom, mitral33, mitral55, tufted)"