# Manifest for Chae et al, 2019 data
[source]
doi = "10.1038/s41593-019-0442-z"
title = "Mosaic representations of odors in the input and output layers of the mouse olfactory bulb"
authors = "H Chae, DR Kepple, WG Bast, VN Murthy, AA Koulakov, DF Albeanu"
tags = "rodent;receptorResponse;academic"
extra = "All raw files available at https://github.com/TeamAlbeanu/mosaic_representations"

[raw]
"raw/glomerular_data/glomerular_responses__main/animal_#*/left_hemibulb/left_hemibulb_ROI_responses.mat" = "glomerular data, left bulb"
"raw/glomerular_data/glomerular_responses__main/animal_#*/right_hemibulb/right_hemibulb_ROI_responses.mat" = "glomerular data, right bulb"
"raw/MT_cell/mitral_cells/33_odors/mc_field_of_view_*.mat" = "cellular data, for the 33 odorant panel"
"raw/MT_cell/mitral_cells/55_odors/mh_field_of_view_*.mat" = "cellular data, for the 55 odorant panel; @ HIGH concentration"
"raw/MT_cell/mitral_cells/55_odors/ml_field_of_view_*.mat" = "cellular data, for the 55 odorant panel; @ LOW concentration"	
"raw/MT_cell/tufted_cells/th_field_of_view_*.mat" = "cellular data, for the 55 odorant panel; @ HIGH concentration"
"raw/MT_cell/tufted_cells/tl_field_of_view_*.mat" = "cellular data, for the 55 odorant panel; @ LOW concentration"

[processed]
"molecules.csv" = "Merged list of molecules used across all experiments (glom, mitral33, mitral55, tufted)"
"stimuli.csv" = "Maps stimulus ID to CID and concentration; coffee assigned CID = -1"
"subjects.csv" = "Maps subject ID to animal, hemibulb, glom or cell, field of view, as applicable"
"behavior_1.csv" = "dF/F responses for all glomerular data, in long format (all subjects & conditions)"
"behavior_2.csv" = "dF/F responses for all mitral cells in the 33 odorant panel experiments; long format"
"behavior_3.csv" = "dF/F responses for all mitral cells in the 55 odorant panel experiments; long format"
"behavior_4.csv" = "dF/F responses for all tufted cells (55 odorant panel); long format"

[code]
"main.py" = "Processing workflow"
