# Manifest for Ravia et al, 2021 data
[source]
doi = "10.1038/s41586-020-2891-7"
title = "A measure of smell enables the creation of olfactory metamers"
authors = "A Ravia, K Snitz, D Honigstein, M Finkel, R Zirler, O Perl, L Secundo, C Laudamiel, D Harel, N Sobel"
tags = "human;odorCharacter;mixtures;academic"

[raw]
"tableS1.csv" = "Supplementary Table 1"
"tableS2.csv" = "Supplementary Table 2"
"tableS3.csv" = "Supplementary Table 2"

[processed]
"molecules.csv" = "Information about odorant molecules used"
"stimuli.csv" = "Maps stimulus ID to molecules/mixtures and experimental conditions used"
"behavior_1.csv" = "Intensity of mixtures used"
"behavior_2.csv" = "Similarity rating test results"
"behavior_3.csv" = "Discrimination test results"

[code]
"main.py" = "Processing workflow"
