# Manifest for IFRA, 2019 data
[source]
doi = ""
title = "Fragrance Ingredient Glossary (2019)"
authors = "The International Fragrance Associations"
extra = "Other representatives of IFRA Regular and Supporting Members, IFRA National
Associations, and members of IFRA National Associations, may request a copy of the
document by visiting ifrafragrance.org/glossary."

[private]
ifra-fragrance-ingredient-glossary---oct-2019.pdf

[raw]
ifra-fragrance-ingredient-glossary---oct-2019.pdf = "Data compiled by The International Fragrance Association"

[parsed]
ifra-fragrance-ingredient-glossary---oct-2019.csv = "The contents of the pdf extracted"

[processed]
main.py = "Processing workflow from parsed to processed data"
molecules.csv = "Identifiable molecules listed in the data"
behavior.csv = "The top 3 descriptors (in order of applicability)"
